services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=jdbc:mysql://localhost:3306/gsmc_db'
      - 'MYSQL_PASSWORD=12345'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
