services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=gsmc_db'
      - 'MYSQL_PASSWORD=12345'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
