version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - redis
    networks:
      - test-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - test-network
networks:
  test-network:
    driver: bridge