spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${RDB_TYPE:mysql}://${RDB_HOST:localhost}:${RDB_PORT:3306}/${RDB_SCHEMA:gsmc_db}
    username: ${RDB_USERNAME:user}
    password: ${RDB_PASSWORD:12345}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
  security:
    user:
      name: prometheus
      password: prometheus
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,https://gsmc-client.vercel.app,https://gsmc.io.kr}
jwt:
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET:f2ba6a534025117d28f915841d241bb1ecb758550803220812374020ef48d3cf}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:86400}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET:f1b1ce8f8c978ab7b6bab79cf406c51fdf2383d1cd1b10bd1080dad3ceb1dda3}
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}
webhook:
  discord:
    url: ${DISCORD_WEBHOOK_URL:https://discordapp.com/api/webhooks/test}
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:dsd}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:sdds}
  bucket:
    name: ${AWS_S3_BUCKET:asdasd}
    region: ${AWS_REGION:ap-northeast-2}

mail:
  host: ${EMAIL_HOST:smtp.gmail.com}
  port: 587
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  ttl: ${EMAIL_TTL:300}
  attempt-limits: 5