spring:
  application:
    name: GSMC-server-V2
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
  cache:
    expire-after-write: ${CACHE_EXPIRE_AFTER_WRITE:60}
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      access: unrestricted
  server:
    port: 8080
server:
  port: ${SERVER_PORT:8080}