spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsmc_db
    username: user
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always
jwt:
  access-token:
    secret: ${ACCESS_TOKEN_SECRET:f2ba6a534025117d28f915841d241bb1ecb758550803220812374020ef48d3cf}
    expiration: ${ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token:
    secret: ${REFRESH_TOKEN_SECRET:f1b1ce8f8c978ab7b6bab79cf406c51fdf2383d1cd1b10bd1080dad3ceb1dda3}
    expiration: ${REFRESH_TOKEN_EXPIRATION:1209600000}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  bucket:
    name: gsmc-dev
    region: ap-northeast-2

mail:
  host: ${EMAIL_HOST:smtp.gmail.com}
  port: 587
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  ttl: 300
  attempt-limits: 5