name: Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run unit tests
        run: ./gradlew clean test --no-daemon
        env:
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
          JPA_DDL_AUTO: ${{ secrets.JPA_DDL_AUTO }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
          JWT_ACCESS_TOKEN_EXPIRATION: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          JWT_REFRESH_TOKEN_EXPIRATION: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TTL: ${{ secrets.EMAIL_TTL }}
          RDB_TYPE: ${{ secrets.RDB_TYPE }}
          RDB_HOST: ${{ secrets.RDB_HOST }}
          RDB_PORT: ${{ secrets.RDB_PORT }}
          RDB_SCHEMA: ${{ secrets.RDB_SCHEMA }}
          RDB_USERNAME: ${{ secrets.RDB_USERNAME }}
          RDB_PASSWORD: ${{ secrets.RDB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: suuuuuuminnnnnn/gsmc-server-v2
          stage: main
          yaml: |
            name: gsmc-server-v2
            app: java@21
            options:
              ports: "8080"
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: ${{ secrets.SPRING_PROFILES_ACTIVE }}
                - name: JPA_DDL_AUTO
                  value: ${{ secrets.JPA_DDL_AUTO }}
                - name: SERVER_PORT
                  value: ${{ secrets.SERVER_PORT }}
                - name: AWS_ACCESS_KEY_ID
                  value: ${{ secrets.AWS_ACCESS_KEY_ID }}
                - name: AWS_SECRET_ACCESS_KEY
                  value: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                - name: AWS_REGION
                  value: ${{ secrets.AWS_REGION }}
                - name: AWS_S3_BUCKET
                  value: ${{ secrets.AWS_S3_BUCKET }}
                - name: JWT_ACCESS_TOKEN_SECRET
                  value: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
                - name: JWT_ACCESS_TOKEN_EXPIRATION
                  value: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}
                - name: JWT_REFRESH_TOKEN_SECRET
                  value: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
                - name: JWT_REFRESH_TOKEN_EXPIRATION
                  value: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
                - name: EMAIL_HOST
                  value: ${{ secrets.EMAIL_HOST }}
                - name: EMAIL_USERNAME
                  value: ${{ secrets.EMAIL_USERNAME }}
                - name: EMAIL_PASSWORD
                  value: ${{ secrets.EMAIL_PASSWORD }}
                - name: EMAIL_TTL
                  value: ${{ secrets.EMAIL_TTL }}
                - name: RDB_TYPE
                  value: ${{ secrets.RDB_TYPE }}
                - name: RDB_HOST
                  value: ${{ secrets.RDB_HOST }}
                - name: RDB_PORT
                  value: ${{ secrets.RDB_PORT }}
                - name: RDB_SCHEMA
                  value: ${{ secrets.RDB_SCHEMA }}
                - name: RDB_USERNAME
                  value: ${{ secrets.RDB_USERNAME }}
                - name: RDB_PASSWORD
                  value: ${{ secrets.RDB_PASSWORD }}
                - name: REDIS_HOST
                  value: ${{ secrets.REDIS_HOST }}
                - name: REDIS_PORT
                  value: ${{ secrets.REDIS_PORT }}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}