name: Build and Test on PR

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify docker-compose.test.yaml exists
        run: ls -la && test -f docker-compose.test.yaml || (echo "docker-compose.test.yaml not found" && exit 1)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run unit tests
        run: ./gradlew clean test --no-daemon
      - name: Build JAR
        run: ./gradlew clean build -x test --no-daemon
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          compose-version: '2.29.2'
      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.test.yaml up -d
          sleep 120
          for i in {1..30}; do
            if curl -s http://localhost:8080/api/v2/health/check | grep -q '"OK"'; then
              echo "Application is up!"
              exit 0
            fi
            echo "Waiting for application... ($i/30)"
            sleep 2
          done
          echo "Application failed to start"
          exit 1
      - name: Run Integration Tests
        run: ./gradlew clean integrationTest --info
      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yaml down